### ISSUE TITLE
Standalone Gradle Plugin

### ISSUE THREAD

**Issue by cortinico** [facebookincubator/ktfmt#164]
Thanks for the great tool 👍

I wrote a standalone Gradle plugin for ktfmt: https://github.com/cortinico/ktfmt-gradle as it was missing (Gradle users had to rely necessarily on Spotless). 

I'm currently using it for a couple of projects of mine and it works fine for my use case.

I'd love to collect some feedback and share it with the community.
I'm also wondering if we could link it in the README?

**Comment by cgrushko** [comment]
Looks great!!
Though - one of the stated goals was to avoid exposing configuration (we listed the rationale in the README file), and the plugin sort of circumvents that. ktfmt is OSS, so it's now in the hands of everyone :)
One concern is that we only test two formatting styles - the default one and a so-called "Google" one. We already ran into situations where e.g., having equal block and continuation indents results in visual bugs, so that's something to keep in mind when trying different combinations.

> I'd love to collect some feedback and share it with the community.

What did you have in mind?

> I'm also wondering if we could link it in the README?

Definitely - do you want to send a PR?

**Comment by cortinico** [comment]
> Though - one of the stated goals was to avoid exposing configuration (we listed the rationale in the README file), and the plugin sort of circumvents that. ktfmt is OSS, so it's now in the hands of everyone :)
> One concern is that we only test two formatting styles - the default one and a so-called "Google" one. We already ran into situations where e.g., having equal block and continuation indents results in visual bugs, so that's something to keep in mind when trying different combinations.

Generally agree. I've tried however to keep consistency with the ktfmt classes visibility. Currently the `FormattingOptions` data class is public:

https://github.com/facebookincubator/ktfmt/blob/3b168867acbd34aeb55f83f51416969bc87ac3ed/core/src/main/java/com/facebook/ktfmt/Formatter.kt#L49-L93

So any other tool that depends on ktfmt has access to it. If this is a concern, that data class should not be exposed. I anyway think it's not a concern as the exposed fields are really limited.

> What did you have in mind?

I think that having the project listed in the README is sufficient to create some awareness 👌 Thanks for the opportunity. If users have feedback on the Gradle side, they can definitely open an issue on the repo 👍
