### ISSUE TITLE
Entropy leak: not removing semicolons

### ISSUE THREAD

**Issue by russellw** [facebookincubator/ktfmt#38]
Very happy with ktfmt so far! (I would like line width to be 120 columns instead of 100, but I understand the reason for not making this configurable.)

One place where entropy from the input is leaking through is semicolons, which are still present in the output. (I imagine the most likely way for this to arise in practice is the way it arose for me: converting Java code by copy pasting it and letting IDEA convert it automatically, which works pretty well a lot of the time but also doesn't remove the semicolons.) Hopefully this would be easy to do?

**Comment by cgrushko** [comment]
I was surprised to find out that it wasn't :) 
The underlying engine (google-java-format's) makes some assumptions about tokens not changing. @cushon might be able to provide more details (I forgot the explanation he previously gave me :|)

(Maybe if we modified the tokenizer to not emit `;` tokens at all? might be an interesting idea.)

**Comment by cushon** [comment]
There are some built-in assertions that formatting only changes whitespace, and doesn't add or remove tokens, because it helps guarantee that reformatting will never affect semantics.

There are some [similar things](https://github.com/google/google-java-format/issues?q=is%3Aissue+is%3Aopen+label%3Anon-whitespace) we'd like to do for Java, but so far I haven't had great ideas for supporting non-whitespace fixes without adding complexity or regressing guarantees around not making semantic changes.

Another option would be do to this is a separate pass, similar to how import fixes are handled.

**Comment by strulovich** [comment]
I'm leaning towards adding an extra pass that would be more aggressive and modify the tree. This will also let us supply a flag for it. I'm against configurations, but removing symbols might be too aggressive for people that call this when they save a file, so it might be useful to support.

@cgrushko, @cushon, how does that sound? We could experiment with ; removal first.

**Comment by cgrushko** [comment]
Sounds good. 
I think we can go ahead with removing `;` without a flag.
If we have luck, kotlin-compiler will just tell us that a symbol is redundant.
